# Generated by Django 2.2.6 on 2019-12-12 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20191212_2201'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
